### ISSUE TITLE
2020.04.29-2020.07.30 | dat consortium call

### ISSUE THREAD

**Issue by serapath** [datdotorg/website#37]
see https://hackmd.io/uj-CO6SaRVSh-Oex4WoWAQ

# Agenda
1. [x] talk about [`datdot-service#7` standard for discovering related hypercores](https://github.com/playproject-io/datdot-service/issues/7)
    * https://github.com/datproject/comm-comm/issues/134
    * https://github.com/tradle/multi-hyperbee/issues/1
2. [x] figure out details about next dat event for presentation of datdot project[`datdot#33` 2020.07.30-21:00pm UTC-0 | datdot presentation
](https://github.com/playproject-io/datdot/issues/33)

---
**Result:**
[![datdot presentation](https://img.youtube.com/vi/6fRECo-mQBw/0.jpg)](https://www.youtube.com/watch?v=6fRECo-mQBw)
[![related feeds](https://img.youtube.com/vi/hzIU5X7g7PI/0.jpg)](https://www.youtube.com/watch?v=hzIU5X7g7PI)

**Comment by cblgh** [comment]
@serapath yo! i think the hypercore standard you've been interviewing people about would be very good to bring up in one of the may meetings of the dat consortium, it's something we're talking a lot about in cabal atm :)

**Comment by serapath** [comment]
thanks a lot :-) I really appreciate the support and didn't expect it.
I answered on the comm-comm issue that we have significant time reserved for pushing this further as soon as we finally finish our first milestone, which keeps us very busy right now

**Comment by serapath** [comment]
@cblgh any news? what's the status in cabal? :-)

**Comment by cblgh** [comment]
@serapath this particular issue/feature is put on the backburner for now in cabal, i think datdot will have to be the one to champion something ^_^

**Comment by serapath** [comment]
thx for the feedback.
will close this issue for now and we will start championing it and tackle it once we get datdot running, which might still need some considerable time, but we'll definitely come back to it at some point :-)

it's all in this issue now:
* https://github.com/playproject-io/datdot-service/issues/7
